/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.goals;

import containers.Services;
import exceptions.ResponseException;
import interfaces.Contextable;
import views.MainFrame;
import views.users.EditSelf;
import utilities.Context;
import helpers.Alert;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import responses.Pagination;
import services.GoalService;
import models.Goal;

/**
 *
 * @author arfanxn
 */
public class Index extends javax.swing.JPanel implements Contextable {

    private Context ctx;
    private GoalService service;
    private Pagination<Goal> pagination;
    private final String[] tableColumnNames = {"Title", "Description"};

    /**
     * Creates new form Index
     *
     * @param ctx
     */
    public Index(Context ctx) {
        this.ctx = ctx;
        this.service = Services.initGoal();
        
        Alert.message(this, ctx, null);
        
        initComponents();
     
        this.fetchGoals();
        this.loadTable();
        this.stylePaginationBtns();
    }
    
    private void fetchGoals() {
        try {
            this.service.index(this.ctx);
            this.ctx.remove("message");
        } catch (ResponseException e) {
            System.out.println(e.getMessage());
        }
        this.pagination = this.ctx.<Pagination<Goal>>get("goals");
    }
    
    private void loadTable() {
        int length = this.pagination.getData().size();
        
        Object[][] data = new Object[length][2];
        for (int i = 0; i < length; i++) {
            Goal goal = this.pagination.getData().get(i);
            data[i][0]= goal.getTitle();
            data[i][1]= goal.getDescription();
        }

        DefaultTableModel tableModel = new DefaultTableModel(data, this.tableColumnNames);
        goalsTable.setModel(tableModel);
    }
    
    private void stylePaginationBtns () {
        if (this.pagination.getNextPageUrl() == null) {
            this.nextBtn.setBackground(Color.decode("#E2E8F0"));
            this.nextBtn.setEnabled(false);
        } else {
            this.nextBtn.setBackground(Color.decode("#3b82f6"));
            this.nextBtn.setEnabled(true);
        }
        
        if (this.pagination.getCurrentPage() == 1) {
            this.firstBtn.setBackground(Color.decode("#E2E8F0"));
            this.firstBtn.setEnabled(false);

            this.prevBtn.setBackground(Color.decode("#E2E8F0"));
            this.prevBtn.setEnabled(false);
        } else {
            this.firstBtn.setBackground(Color.decode("#3b82f6"));
            this.firstBtn.setEnabled(true);

            this.prevBtn.setBackground(Color.decode("#3b82f6"));
            this.prevBtn.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbarPanel = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        goalsTable = new javax.swing.JTable();
        formPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        prevBtn = new javax.swing.JButton();
        firstBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(59, 130, 246));
        setPreferredSize(new java.awt.Dimension(700, 500));

        navbarPanel.setBackground(new java.awt.Color(245, 158, 11));

        dashboardLabel.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setText("Dashboard");

        accountLabel.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        accountLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountLabel.setText("Account");
        accountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navbarPanelLayout = new javax.swing.GroupLayout(navbarPanel);
        navbarPanel.setLayout(navbarPanelLayout);
        navbarPanelLayout.setHorizontalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accountLabel)
                .addGap(14, 14, 14)
                .addComponent(dashboardLabel)
                .addGap(25, 25, 25))
        );
        navbarPanelLayout.setVerticalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dashboardLabel)
                    .addComponent(accountLabel))
                .addGap(14, 14, 14))
        );

        scrollPane.setBackground(new java.awt.Color(245, 158, 11));
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        goalsTable.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        goalsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        goalsTable.setToolTipText("");
        goalsTable.setCellSelectionEnabled(false);
        goalsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        goalsTable.setDropMode(javax.swing.DropMode.ON);
        goalsTable.setRowHeight(25);
        goalsTable.setRowSelectionAllowed(true);
        goalsTable.setSelectionBackground(java.awt.Color.blue);
        goalsTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        goalsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        goalsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        goalsTable.setShowGrid(true);
        goalsTable.setSurrendersFocusOnKeystroke(true);
        goalsTable.getTableHeader().setReorderingAllowed(false);
        goalsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goalsTableMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(goalsTable);
        goalsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        formPanel.setBackground(new java.awt.Color(59, 130, 246));

        searchField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N

        addBtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addComponent(searchField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nextBtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        prevBtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        prevBtn.setText("Prev");
        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });

        firstBtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        firstBtn.setText("First");
        firstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLabelMouseClicked
        MainFrame.getInstance().setComponent(new EditSelf(this.ctx));
    }//GEN-LAST:event_accountLabelMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            this.service.add(this.ctx);
            Alert.message(this, this.ctx, null);
            this.loadTable();
        } catch (ResponseException e) {
            Alert.message(formPanel, e.getMessage(), null);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        this.ctx.put("keyword", this.searchField.getText());
        this.fetchGoals();
        this.loadTable();
        this.stylePaginationBtns();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        this.ctx.put("page", this.pagination.getCurrentPage() + 1);
        this.fetchGoals();
        this.loadTable();
        this.stylePaginationBtns();
    }//GEN-LAST:event_nextBtnActionPerformed

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
        this.ctx.put("page", this.pagination.getCurrentPage() - 1);
        this.fetchGoals();
        this.loadTable();
        this.stylePaginationBtns();
    }//GEN-LAST:event_prevBtnActionPerformed

    private void firstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstBtnActionPerformed
        this.ctx.put("page", 1);
        this.fetchGoals();
        this.loadTable();
        this.stylePaginationBtns();
    }//GEN-LAST:event_firstBtnActionPerformed

    private void goalsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goalsTableMouseClicked
        int row = goalsTable.getSelectedRow();
        System.out.println("selected row is: "+ String.valueOf(row));
        MainFrame.getInstance().setComponent(new Edit(this.ctx));
    }//GEN-LAST:event_goalsTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JButton firstBtn;
    private javax.swing.JPanel formPanel;
    private javax.swing.JTable goalsTable;
    private javax.swing.JPanel navbarPanel;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton prevBtn;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
